---
title: "Census Geocoder"
author: "Josh DeLaRosa"
date: "`r format(Sys.time(), '%Y %b %d')`"
output: 
  html_document: 
    highlight: tango
    theme: united
    toc: yes
    toc_float: yes
---

# Function Creation
Create function for Census geography look-up using lat/long
```{r}
census_latlong<-function (street, city, state) 
{
  call_start <- "https://geocoding.geo.census.gov/geocoder/locations/address?"
  url <- paste0("street=", utils::URLencode(street), "&city=", 
                utils::URLencode(city), "&state=", state)
  call_end <- "&benchmark=4&format=json"
  url_full <- paste0(call_start, url, call_end)
  r <- httr::GET(url_full)
  httr::stop_for_status(r)
  response <- httr::content(r)
  if (length(response$result$addressMatches) == 0) {
    message(paste0("Address (", street, " ", city, " ", 
                   state, ") returned no address matches. An NA was returned."))
    return(NA_character_)
  }
  else {
    if (length(response$result$addressMatches) > 1) {
      message(paste0("Address (", street, " ", city, " ", 
                     state, ") returned more than one address match. The first match was returned."))
    }
    return(paste(response$result$addressMatches[[1]]$coordinates$y,response$result$addressMatches[[1]]$coordinates$x,sep=','))
  }
}
```

Create function for Census geography look-up using address
```{r}
call_geolocator2<-function (street, city, state) 
{
  call_start <- "https://geocoding.geo.census.gov/geocoder/geographies/address?"
  url <- paste0("street=", utils::URLencode(street), "&city=", 
                utils::URLencode(city), "&state=", state)
  call_end <- "&benchmark=9&vintage=910&layers=14&format=json"
  url_full <- paste0(call_start, url, call_end)
  r <- httr::GET(url_full)
  httr::stop_for_status(r)
  response <- httr::content(r)
  if (length(response$result$addressMatches) == 0) {
    message(paste0("Address (", street, " ", city, " ", 
                   state, ") returned no address matches. An NA was returned."))
    return(NA_character_)
  }
  else {
    if (length(response$result$addressMatches) > 1) {
      message(paste0("Address (", street, " ", city, " ", 
                     state, ") returned more than one address match. The first match was returned."))
    }
    return(response$result$addressMatches[[1]]$geographies$`Census Blocks`[[1]]$GEOID)
  }
}
```

Create function that uses the `call_geolocator2` and `census_latlong`
```{r}
append_geoid2<-function (address, geoid_type = "bl") 
{
  if ("lat" %in% colnames(address) && "lon" %in% colnames(address)) {
    geoids <- vector(mode = "character", length = nrow(address))
    for (i in 1:nrow(address)) {
      geoids[i] <- call_geolocator_latlon2(address$lat[i], 
                                          address$lon[i])
    }
  }
  else {
    geoids <- vector(mode = "character", length = nrow(address))
    for (i in 1:nrow(address)) {
      geoids[i] <- call_geolocator2(as.character(address$street[i]), 
                                   as.character(address$city[i]), as.character(address$state[i]))
    }
  }
  address <- dplyr::mutate(address, geoid = geoids)
  if (geoid_type == "co") {
    end <- 5
  }
  else if (geoid_type == "tr") {
    end <- 11
  }
  else if (geoid_type == "bg") {
    end <- 12
  }
  else {
    end <- 15
  }
  address <- dplyr::mutate(address, geoid = ifelse(is.na(geoid), 
                                                   NA_character_, substr(geoid, 1, end)))
  return(address)
}
```

Create function to geocode address and pick-up lat/long
```{r}
  call_geolocator_latlon2<-function (lat, lon) 
  {
    call_start <- "https://geocoding.geo.census.gov/geocoder/geographies/coordinates?"
    url <- paste0("x=", lon, "&y=", lat)
    call_end <- "&benchmark=9&vintage=910&layers=14&format=json"
    url_full <- paste0(call_start, url, call_end)
    r <- httr::GET(url_full)
    httr::stop_for_status(r)
    response <- httr::content(r)
    if (length(response$result$geographies$`Census Blocks`) == 
        0) {
      message(paste0("Lat/lon (", lat, ", ", lon, ") returned no geocodes. An NA was returned."))
      return(NA_character_)
    }
    else {
      if (length(response$result$geographies$`Census Blocks`) > 
          1) {
        message(paste0("Lat/lon (", lat, ", ", lon, ") returned more than geocode. The first match was returned."))
      }
      return(response$result$geographies$`Census Blocks`[[1]]$GEOID)
    }
  }
```

# Geocode
Set library
```{r}
library("tidyverse")
```

Test geocoding function
```{r}
census_latlong("42-09 28th St"," Long Island City", "NY")
```

Create test dataset
```{r}
# create dataset
street<-c('42-09 28th St','160 W 100th St','350 Linwood St')
city<-c('Long Island City','New York','Brooklyn')
state<-c('NY','NY','NY')

DOH_BSA <- data.frame(street, city, state) %>%
  mutate_if(is.factor, as.character)  # turns factor into character

glimpse(DOH_BSA)
```

Geocode the data
```{r}
DOH_geocoded<-DOH_BSA %>%
  mutate(LL=mapply(census_latlong,street,city,state)) %>% # returns lat/long
  separate(LL, into = c("lat", "long"),sep = ",") %>% #splits lat/long response into 2 columns
  append_geoid2('bl')  %>% # get census geo for addresses
  mutate(fip_state= str_sub(geoid,1,2)) %>% # begin to parse geography data
  mutate(fip_county= str_sub(geoid,3,5)) %>%
  mutate(fip_tract= str_sub(geoid,6,11)) %>% 
  mutate(fip_block= str_sub(geoid,12,15))

DOH_geocoded
```
